# Generated by Django 4.2.29 on 2026-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_adminemail_logincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminemail',
            name='name',
            field=models.CharField(default='TALI Staff', max_length=150),
        ),
    ]
