# Generated by Django 4.2.29 on 2026-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_adminemail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_mode',
            field=models.CharField(choices=[('FLUTTERWAVE', 'Flutterwave'), ('BANK_TRANSFER', 'Bank Transfer'), ('MANUAL', 'Manual Entry'), ('INTENT', 'Payment Intent')], max_length=20),
        ),
    ]
