# Generated by Django 4.2.29 on 2026-04-14 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_donation_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='celebration_count',
            field=models.IntegerField(default=0),
        ),
    ]
